folder_in: /home/user2/tst
folder_out: /home/user2/out
folder_ext:  /home/user2/folder1
folder_ext2: /home/user2/folder2
count: 3
ip: 0.0.0.0
prt: 22
user: user2
passwd: "user2"
pkgname: p7zip-full
type: 7z